// <auto-generated />
using System;
using GrossistenApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrossistenApi.Migrations
{
    [DbContext(typeof(GrossistenApiDatabaseContext))]
    [Migration("20250602180259_fixedTestDataProductsOnReceipts")]
    partial class fixedTestDataProductsOnReceipts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GrossistenApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArticleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ReceiptId")
                        .HasColumnType("int");

                    b.Property<bool?>("ShowInAvailableToPurchase")
                        .HasColumnType("bit");

                    b.Property<bool?>("ShowInStock")
                        .HasColumnType("bit");

                    b.Property<bool?>("ShowOnReceipt")
                        .HasColumnType("bit");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductsTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleNumber = "4006381333931",
                            Category = "Kläder",
                            Description = "Klassisk vit t-shirt",
                            Price = 199.0,
                            Quantity = 150,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "L",
                            Title = "T-shirt"
                        },
                        new
                        {
                            Id = 2,
                            ArticleNumber = "5012345678900",
                            Category = "Kläder",
                            Description = "Blå jeans, normal passform",
                            Price = 499.0,
                            Quantity = 80,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "M",
                            Title = "Jeans"
                        },
                        new
                        {
                            Id = 3,
                            ArticleNumber = "5023456789012",
                            Category = "Skor",
                            Description = "Löparsneakers",
                            Price = 899.0,
                            Quantity = 60,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "S",
                            Title = "Sneakers"
                        },
                        new
                        {
                            Id = 4,
                            ArticleNumber = "6012345678901",
                            Category = "Kläder",
                            Description = "Grå hoodie",
                            Price = 599.0,
                            Quantity = 40,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "M",
                            Title = "Hoodie"
                        },
                        new
                        {
                            Id = 5,
                            ArticleNumber = "7012345678902",
                            Category = "Accessoarer",
                            Description = "Basebollkeps",
                            Price = 149.0,
                            Quantity = 200,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "M",
                            Title = "Keps"
                        },
                        new
                        {
                            Id = 6,
                            ArticleNumber = "8001234567890",
                            Category = "Accessoarer",
                            Description = "Analog klocka",
                            Price = 1299.0,
                            Quantity = 30,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "25 cm",
                            Title = "Klocka"
                        },
                        new
                        {
                            Id = 7,
                            ArticleNumber = "9001234567891",
                            Category = "Elektronik",
                            Description = "33 cm ultrabook",
                            Price = 9999.0,
                            Quantity = 0,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "33 cm",
                            Title = "Bärbar dator"
                        },
                        new
                        {
                            Id = 8,
                            ArticleNumber = "3001234567892",
                            Category = "Hem",
                            Description = "Keramisk mugg 350 ml",
                            Price = 99.0,
                            Quantity = 120,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "8 cm",
                            Title = "Kaffemugg"
                        },
                        new
                        {
                            Id = 9,
                            ArticleNumber = "2001234567893",
                            Category = "Accessoarer",
                            Description = "Reseryggsäck 20 L",
                            Price = 799.0,
                            Quantity = 50,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "20 L",
                            Title = "Ryggsäck"
                        },
                        new
                        {
                            Id = 10,
                            ArticleNumber = "1001234567894",
                            Category = "Accessoarer",
                            Description = "UV-skydd",
                            Price = 399.0,
                            Quantity = 75,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "52 mm",
                            Title = "Solglasögon"
                        },
                        new
                        {
                            Id = 11,
                            ArticleNumber = "1101234567895",
                            Category = "Böcker",
                            Description = "The Great Gatsby",
                            Price = 149.0,
                            Quantity = 100,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "13×20 cm",
                            Title = "Bok"
                        },
                        new
                        {
                            Id = 12,
                            ArticleNumber = "1201234567896",
                            Category = "Leksaker",
                            Description = "Träschackspel",
                            Price = 349.0,
                            Quantity = 20,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "40×40 cm",
                            Title = "Schackspel"
                        },
                        new
                        {
                            Id = 13,
                            ArticleNumber = "1301234567897",
                            Category = "Leksaker",
                            Description = "Superhjältefigur",
                            Price = 249.0,
                            Quantity = 60,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "15 cm",
                            Title = "Actionfigur"
                        },
                        new
                        {
                            Id = 14,
                            ArticleNumber = "1401234567898",
                            Category = "Hem",
                            Description = "24-delars set i rostfritt stål",
                            Price = 599.0,
                            Quantity = 80,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "30×20×5 cm",
                            Title = "Bestickset"
                        },
                        new
                        {
                            Id = 15,
                            ArticleNumber = "1501234567899",
                            Category = "Hem",
                            Description = "LED-skrivbordslampa",
                            Price = 349.0,
                            Quantity = 35,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "45 cm",
                            Title = "Skrivbordslampa"
                        },
                        new
                        {
                            Id = 16,
                            ArticleNumber = "1601234567800",
                            Category = "Skönhet",
                            Description = "Blommig doft 50 ml",
                            Price = 799.0,
                            Quantity = 0,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "50 ml",
                            Title = "Parfym"
                        },
                        new
                        {
                            Id = 17,
                            ArticleNumber = "1701234567801",
                            Category = "Elektronik",
                            Description = "Trådlösa over-ear",
                            Price = 1299.0,
                            Quantity = 45,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "15×18 cm",
                            Title = "Hörlurar"
                        },
                        new
                        {
                            Id = 18,
                            ArticleNumber = "1801234567802",
                            Category = "Sport",
                            Description = "Halkfri 6 mm",
                            Price = 299.0,
                            Quantity = 0,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "183×61 cm",
                            Title = "Yogamatta"
                        },
                        new
                        {
                            Id = 19,
                            ArticleNumber = "1901234567803",
                            Category = "Utomhus",
                            Description = "Tält för 2 personer",
                            Price = 1599.0,
                            Quantity = 15,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "210×140×110 cm",
                            Title = "Tält"
                        },
                        new
                        {
                            Id = 20,
                            ArticleNumber = "2101234567804",
                            Category = "Husdjur",
                            Description = "Hållbar tuggleksak",
                            Price = 129.0,
                            Quantity = 90,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "15×5 cm",
                            Title = "Hundleksak"
                        },
                        new
                        {
                            Id = 21,
                            ArticleNumber = "2201234567805",
                            Category = "Kläder",
                            Description = "Vattentät jacka",
                            Price = 899.0,
                            Quantity = 30,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "L",
                            Title = "Jacka"
                        },
                        new
                        {
                            Id = 22,
                            ArticleNumber = "2301234567806",
                            Category = "Skor",
                            Description = "Sommarsandaler",
                            Price = 349.0,
                            Quantity = 45,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "38",
                            Title = "Sandaler"
                        },
                        new
                        {
                            Id = 23,
                            ArticleNumber = "2401234567807",
                            Category = "Accessoarer",
                            Description = "Läderbälte",
                            Price = 299.0,
                            Quantity = 60,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "M",
                            Title = "Skärp"
                        },
                        new
                        {
                            Id = 24,
                            ArticleNumber = "2501234567808",
                            Category = "Elektronik",
                            Description = "6,5\" skärm, 128GB",
                            Price = 5999.0,
                            Quantity = 25,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = true,
                            Size = "16×7,5×0,8 cm",
                            Title = "Smartphone"
                        },
                        new
                        {
                            Id = 25,
                            ArticleNumber = "2601234567809",
                            Category = "Hem",
                            Description = "Bomull, 45×45 cm",
                            Price = 199.0,
                            Quantity = 100,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "45×45 cm",
                            Title = "Prydnadskudde"
                        },
                        new
                        {
                            Id = 26,
                            ArticleNumber = "2701234567810",
                            Category = "Böcker",
                            Description = "Vegetariska recept",
                            Price = 249.0,
                            Quantity = 80,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "18×24 cm",
                            Title = "Kokbok"
                        },
                        new
                        {
                            Id = 27,
                            ArticleNumber = "2801234567811",
                            Category = "Leksaker",
                            Description = "1000 bitar landskap",
                            Price = 159.0,
                            Quantity = 70,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "50×70 cm",
                            Title = "Pussel"
                        },
                        new
                        {
                            Id = 28,
                            ArticleNumber = "2901234567812",
                            Category = "Skönhet",
                            Description = "Fuktgivande 200 ml",
                            Price = 129.0,
                            Quantity = 50,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "200 ml",
                            Title = "Lotion"
                        },
                        new
                        {
                            Id = 29,
                            ArticleNumber = "3001234567813",
                            Category = "Sport",
                            Description = "Strl S/M, justerbar",
                            Price = 499.0,
                            Quantity = 40,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "S/M",
                            Title = "Cykelhjälm"
                        },
                        new
                        {
                            Id = 30,
                            ArticleNumber = "3101234567814",
                            Category = "Utomhus",
                            Description = "Lättvikts för camping",
                            Price = 699.0,
                            Quantity = 20,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "210×75 cm",
                            Title = "Sovsäck"
                        },
                        new
                        {
                            Id = 31,
                            ArticleNumber = "3201234567815",
                            Category = "Husdjur",
                            Description = "Fjäder på pinne",
                            Price = 79.0,
                            Quantity = 120,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "30 cm",
                            Title = "Kattleksak"
                        },
                        new
                        {
                            Id = 32,
                            ArticleNumber = "3301234567816",
                            Category = "Kläder",
                            Description = "Svart t-shirt",
                            Price = 199.0,
                            Quantity = 90,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "M",
                            Title = "T-shirt"
                        },
                        new
                        {
                            Id = 33,
                            ArticleNumber = "3401234567817",
                            Category = "Skor",
                            Description = "Vandringskängor",
                            Price = 1299.0,
                            Quantity = 35,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "42",
                            Title = "Kängor"
                        },
                        new
                        {
                            Id = 34,
                            ArticleNumber = "3501234567818",
                            Category = "Accessoarer",
                            Description = "Läder, svart",
                            Price = 349.0,
                            Quantity = 55,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "10×8 cm",
                            Title = "Plånbok"
                        },
                        new
                        {
                            Id = 35,
                            ArticleNumber = "3601234567819",
                            Category = "Elektronik",
                            Description = "Portabel, vattentät",
                            Price = 799.0,
                            Quantity = 45,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "15×8×7 cm",
                            Title = "Bluetooth-högtalare"
                        },
                        new
                        {
                            Id = 36,
                            ArticleNumber = "3701234567820",
                            Category = "Hem",
                            Description = "Analog träfinish",
                            Price = 299.0,
                            Quantity = 65,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "20 cm",
                            Title = "Väggklocka"
                        },
                        new
                        {
                            Id = 37,
                            ArticleNumber = "3801234567821",
                            Category = "Böcker",
                            Description = "Moderna klassiker",
                            Price = 179.0,
                            Quantity = 90,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "12×19 cm",
                            Title = "Roman"
                        },
                        new
                        {
                            Id = 38,
                            ArticleNumber = "3901234567822",
                            Category = "Leksaker",
                            Description = "Strategispel för 2–4",
                            Price = 399.0,
                            Quantity = 40,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "30×30×5 cm",
                            Title = "Brädspel"
                        },
                        new
                        {
                            Id = 39,
                            ArticleNumber = "4001234567823",
                            Category = "Skönhet",
                            Description = "Ögonskugga & läppstift",
                            Price = 499.0,
                            Quantity = 30,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "20×15×3 cm",
                            Title = "Sminkkit"
                        },
                        new
                        {
                            Id = 40,
                            ArticleNumber = "4101234567824",
                            Category = "Sport",
                            Description = "2×5 kg, justerbart",
                            Price = 899.0,
                            Quantity = 25,
                            ShowInAvailableToPurchase = true,
                            ShowInStock = true,
                            ShowOnReceipt = false,
                            Size = "25 cm",
                            Title = "Hantelset"
                        },
                        new
                        {
                            Id = 41,
                            ArticleNumber = "5012345678900",
                            Category = "Kläder",
                            Description = "Blå jeans, normal passform",
                            Price = 499.0,
                            Quantity = 5,
                            ReceiptId = 2,
                            ShowInAvailableToPurchase = false,
                            ShowInStock = false,
                            ShowOnReceipt = true,
                            Size = "M",
                            Title = "Jeans"
                        },
                        new
                        {
                            Id = 42,
                            ArticleNumber = "6012345678901",
                            Category = "Kläder",
                            Description = "Grå hoodie",
                            Price = 599.0,
                            Quantity = 4,
                            ReceiptId = 4,
                            ShowInAvailableToPurchase = false,
                            ShowInStock = false,
                            ShowOnReceipt = true,
                            Size = "M",
                            Title = "Hoodie"
                        },
                        new
                        {
                            Id = 43,
                            ArticleNumber = "8001234567890",
                            Category = "Accessoarer",
                            Description = "Analog klocka",
                            Price = 1299.0,
                            Quantity = 3,
                            ReceiptId = 6,
                            ShowInAvailableToPurchase = false,
                            ShowInStock = false,
                            ShowOnReceipt = true,
                            Size = "25 cm",
                            Title = "Klocka"
                        },
                        new
                        {
                            Id = 44,
                            ArticleNumber = "1101234567895",
                            Category = "Böcker",
                            Description = "The Great Gatsby",
                            Price = 149.0,
                            Quantity = 10,
                            ReceiptId = 1,
                            ShowInAvailableToPurchase = false,
                            ShowInStock = false,
                            ShowOnReceipt = true,
                            Size = "13×20 cm",
                            Title = "Bok"
                        },
                        new
                        {
                            Id = 45,
                            ArticleNumber = "1201234567896",
                            Category = "Leksaker",
                            Description = "Träschackspel",
                            Price = 349.0,
                            Quantity = 3,
                            ReceiptId = 2,
                            ShowInAvailableToPurchase = false,
                            ShowInStock = false,
                            ShowOnReceipt = true,
                            Size = "40×40 cm",
                            Title = "Schackspel"
                        },
                        new
                        {
                            Id = 46,
                            ArticleNumber = "1301234567897",
                            Category = "Leksaker",
                            Description = "Superhjältefigur",
                            Price = 249.0,
                            Quantity = 6,
                            ReceiptId = 3,
                            ShowInAvailableToPurchase = false,
                            ShowInStock = false,
                            ShowOnReceipt = true,
                            Size = "15 cm",
                            Title = "Actionfigur"
                        },
                        new
                        {
                            Id = 47,
                            ArticleNumber = "1401234567898",
                            Category = "Hem",
                            Description = "24-delars set i rostfritt stål",
                            Price = 599.0,
                            Quantity = 8,
                            ReceiptId = 4,
                            ShowInAvailableToPurchase = false,
                            ShowInStock = false,
                            ShowOnReceipt = true,
                            Size = "30×20×5 cm",
                            Title = "Bestickset"
                        },
                        new
                        {
                            Id = 48,
                            ArticleNumber = "1501234567899",
                            Category = "Hem",
                            Description = "LED-skrivbordslampa",
                            Price = 349.0,
                            Quantity = 6,
                            ReceiptId = 5,
                            ShowInAvailableToPurchase = false,
                            ShowInStock = false,
                            ShowOnReceipt = true,
                            Size = "45 cm",
                            Title = "Skrivbordslampa"
                        },
                        new
                        {
                            Id = 49,
                            ArticleNumber = "1601234567800",
                            Category = "Skönhet",
                            Description = "Blommig doft 50 ml",
                            Price = 799.0,
                            Quantity = 5,
                            ReceiptId = 6,
                            ShowInAvailableToPurchase = false,
                            ShowInStock = false,
                            ShowOnReceipt = true,
                            Size = "50 ml",
                            Title = "Parfym"
                        },
                        new
                        {
                            Id = 50,
                            ArticleNumber = "1701234567801",
                            Category = "Elektronik",
                            Description = "Trådlösa over-ear",
                            Price = 1299.0,
                            Quantity = 7,
                            ReceiptId = 7,
                            ShowInAvailableToPurchase = false,
                            ShowInStock = false,
                            ShowOnReceipt = true,
                            Size = "15×18 cm",
                            Title = "Hörlurar"
                        },
                        new
                        {
                            Id = 51,
                            ArticleNumber = "1801234567802",
                            Category = "Sport",
                            Description = "Halkfri 6 mm",
                            Price = 299.0,
                            Quantity = 8,
                            ReceiptId = 8,
                            ShowInAvailableToPurchase = false,
                            ShowInStock = false,
                            ShowOnReceipt = true,
                            Size = "183×61 cm",
                            Title = "Yogamatta"
                        },
                        new
                        {
                            Id = 52,
                            ArticleNumber = "1901234567803",
                            Category = "Utomhus",
                            Description = "Tält för 2 personer",
                            Price = 1599.0,
                            Quantity = 10,
                            ReceiptId = 9,
                            ShowInAvailableToPurchase = false,
                            ShowInStock = false,
                            ShowOnReceipt = true,
                            Size = "210×140×110 cm",
                            Title = "Tält"
                        },
                        new
                        {
                            Id = 53,
                            ArticleNumber = "2101234567804",
                            Category = "Husdjur",
                            Description = "Hållbar tuggleksak",
                            Price = 129.0,
                            Quantity = 9,
                            ReceiptId = 10,
                            ShowInAvailableToPurchase = false,
                            ShowInStock = false,
                            ShowOnReceipt = true,
                            Size = "15×5 cm",
                            Title = "Hundleksak"
                        });
                });

            modelBuilder.Entity("GrossistenApi.Models.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateAndTimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("showAsIncomingReceipt")
                        .HasColumnType("bit");

                    b.Property<bool?>("showAsOutgoingReceipt")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ReceiptsTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAndTimeCreated = new DateTime(2025, 5, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            WorkerName = "Peter Nilsson",
                            showAsIncomingReceipt = true,
                            showAsOutgoingReceipt = false
                        },
                        new
                        {
                            Id = 2,
                            DateAndTimeCreated = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            WorkerName = "Maria Andersson",
                            showAsIncomingReceipt = true,
                            showAsOutgoingReceipt = false
                        },
                        new
                        {
                            Id = 3,
                            DateAndTimeCreated = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            WorkerName = "Johan Karlsson",
                            showAsIncomingReceipt = true,
                            showAsOutgoingReceipt = false
                        },
                        new
                        {
                            Id = 4,
                            DateAndTimeCreated = new DateTime(2025, 4, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            WorkerName = "Elin Larsson",
                            showAsIncomingReceipt = true,
                            showAsOutgoingReceipt = false
                        },
                        new
                        {
                            Id = 5,
                            DateAndTimeCreated = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            WorkerName = "Lars Gustafsson",
                            showAsIncomingReceipt = true,
                            showAsOutgoingReceipt = false
                        },
                        new
                        {
                            Id = 6,
                            DateAndTimeCreated = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            WorkerName = "Anna Sjöberg",
                            showAsIncomingReceipt = false,
                            showAsOutgoingReceipt = true
                        },
                        new
                        {
                            Id = 7,
                            DateAndTimeCreated = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            WorkerName = "Oskar Lindqvist",
                            showAsIncomingReceipt = false,
                            showAsOutgoingReceipt = true
                        },
                        new
                        {
                            Id = 8,
                            DateAndTimeCreated = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            WorkerName = "Sara Ek",
                            showAsIncomingReceipt = false,
                            showAsOutgoingReceipt = true
                        },
                        new
                        {
                            Id = 9,
                            DateAndTimeCreated = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            WorkerName = "Fredrik Öberg",
                            showAsIncomingReceipt = false,
                            showAsOutgoingReceipt = true
                        },
                        new
                        {
                            Id = 10,
                            DateAndTimeCreated = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            WorkerName = "Maria Johansson",
                            showAsIncomingReceipt = false,
                            showAsOutgoingReceipt = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
